### PR TITLE
Enables orgtbl-mode in results buffer

### PR DESCRIPTION
**Pull request by alf-mindshift**
Implements #97. Note that this pull request builds on top of #98. Let me know if I should rebase it on master instead.

### CODE REVIEW

**Comment by alf-mindshift** [comment]
I'll rebase this on master. I'll also look into the failing tests.

**Comment by kostafey** [comment]
@alf-mindshift, please keep the previous implementation optional.
Since we can use different Emacs table implementations (more than two in the future) could you please add a selector like this:
```lisp
(defcustom ejc-result-table-impl 'orgtbl-mode
  "Set mode for result-set table. Possible values are one of:
'orgtbl-mode
'ejc-result-mode."
   ...
```

**Comment by alf-mindshift** [comment]
I'll keep the previous implementation optional.

Since orgtbl-mode is a minor mode and ejc-result-mode is a major mode, I was thinking of keeping ejc-result-mode and optionally enable orgtbl-mode.

How about the undo and read/write stuff? If the user prefers the old implementation, does that include these things or can we break backwards compatibility there?

**Comment by kostafey** [comment]
> Since orgtbl-mode is a minor mode and ejc-result-mode is a major mode, I was thinking of keeping ejc-result-mode and optionally enable orgtbl-mode.

The only reason to keep `ejc-result-mode` with `orgtbl-mode` minor-mode is `mode-name`. `font-lock`  is rewritten by  `orgtbl-mode`. I think it's ok.

> How about the undo and read/write stuff? If the user prefers the old implementation, does that include these things or can we break backwards compatibility there?

The main reason to disable undo is to reduce memory consumption. This makes sense for some kinds of tasks. Yes, it should be preserved. Read-only is ok to preserve too.

**Comment by alf** [comment]
What if we truncate the undo history when we display a result? In this case, unless you actually edit the buffer manually the undo history will always be empty.

Of course, maybe Emacs saves additional memory if undo is completely disabled?

**Comment by alf-mindshift** [comment]
Just a heads up, I haven't had time to implement the requested changes yet. Does you merging the original pull request mean you have changed your mind, or should I make the requested changes and send a new pull request?

**Comment by kostafey** [comment]
> What if we truncate the undo history when we display a result? In this case, unless you actually edit the buffer manually the undo history will always be empty.

I guess it's a best probable solution here.

> Does you merging the original pull request mean you have changed your mind, or should I make the requested changes and send a new pull request?

Nothing changed. Please provide an optional solution in the new pull request.

**Comment by alf-mindshift** [comment]
It's still not clear to me if the optional behaviour keeps the old table syntax or if it just disables the orgtbl-mode and sets the buffer read only by default.

**Comment by kostafey** [comment]
@alf-mindshift well, it's not very hard to pass an additional parameter to keep the old table syntax since it's a bit more compact in terms of line length.

**Pull request merged**
