### PR TITLE
Add a helper command to easily connect to any local SQLite database

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by stardiviner** [comment]
This kind of helper command also can be used for other similar Database Drivers which is local file could be anywhere.

BTW, I'm consider whether it is possible to use Org Mode source block header arguments as parameter for auto creating connection and connect. The problem in this is how to find corresponding property driver info.

For database like MySQL, PostgreSQL etc, I wonder is it possible fetch available db in database, then user will free from manually create connection a lot. I don't know whether this is possible.

**Comment by kostafey** [comment]
But what about the connection configuration persistence on Emacs restarts. I think we can add something like: 
```lisp
(defcustom ejc-config-file-path (file-truename "~/.emacs.d/ejc-config.el")
  ...
```
and save data to it and load on Emacs restarts.

Furthermore, I'd prefer to use single connections creation helper function for all kinds of databases.
Moreover, it should be an automatic JDBC drivers check & download engine to reduce manual configuration efforts.
Ok, I'll dig more in this direction a bit later.

**Comment by stardiviner** [comment]
> But what about the connection configuration persistence on Emacs restarts.

I did not want to give up connection configuration persistence. But for static local file type database, they can be more dynamic. Because user can't add connection configuration one by one. And use one db file temporary and will be very convinient.

About your mentioned method to persistent connection configuration. I agree with that. I think it's a good and simple solution. Also it isolated connection authentication sensitive info like "password" etc from Emacs init files configuration which some people like me managed by Git might uploaded by mistake.

> Furthermore, I'd prefer to use single connections creation helper function for all kinds of databases.

I did have a thinking on this direction. But I can't implement it, and I warry about this might be over too much to code. I'm not sure it will be easy to do. So have not raised it up.

> Moreover, it should be an automatic JDBC drivers check & download engine to reduce manual configuration efforts.

About downloading is done by `clj`. But about drivers checking, I can't come up with any good idea to archive that simply.

**Comment by kostafey** [comment]
Closed since `ejc-connect-interactive` - a generic for all kinds of databases function will be used for creating new connections interactively: https://github.com/kostafey/ejc-sql/commit/08a34d1a6904054ae5b78cb2301bda980592fb89

**Pull request closed without merging**
