### PR TITLE
try async db call for sql queries

### PR DESCRIPTION
**Pull request by tutysara**
I tried to make use of async execution for long running operations. Table query is the one that I do most so, started with it and converted it to use async style. See if this looks good.

### CODE REVIEW

**Comment by kostafey** [comment]
Ok, I've updated it a bit. I think it should be fun to add something like [spinner.el](https://github.com/Malabarba/spinner.el)

**Comment by kostafey** [comment]
@tutysara, could you authorize in GitHub via email to be highlighted as commit author?

**Comment by tutysara** [comment]
Sure, working on it. ty

**Comment by tutysara** [comment]
Yeah, we should indicate a query is running in background, will have a look at spinner.el

**Comment by kostafey** [comment]
I'm afraid that async receiving DB cache requires a bit more effort than common SQL queries.

**Comment by tutysara** [comment]
> @tutysara, could you authorize in GitHub via email to be highlighted as commit author?

I verified my other email address to enable highlighting the commit.

> I'm afraid that async receiving DB structure cache requires a bit more effort than common SQL queries.

I haven't taken a good look at that function, lets see what best we can do for it

**Pull request merged**
